# -*- coding: utf-8 -*-
"""record&callClassifier.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1efwVhWDMwSOLFZMY6k6rrEjyYRnZ-Irf
"""

import os
import datetime
import subprocess

samples_path = '/home/samus/Music/buffer/'
# samples_folder = '/content/drive/MyDrive/samples/'
timestamp = datetime.datetime.now().strftime('%Y_%m_%d-%H_%M_%S')
# filename = samples_folder + timestamp + ".wav"
filename = samples_path + timestamp + ".wav"
print(timestamp)

cmd = 'arecord -D hw:3,0 -t wav -f S16_LE -r 44100 -c 2 -d 3 ' + filename

while True:
    os.system(cmd) #records a three second sample

#subprocess.run(["python" , "live_sound_classifier_only.py"])
